export default {
    COINBASE_OAUTH_SUCCESS:'COINBASE_OAUTH_SUCCESS',
    LOGIN_REQUEST : 'LOGIN_REQUEST',
    LOGIN_REQUEST_SUCCESS:'LOGIN_REQUEST_SUCCESS',
    LOGIN_REQUEST_FAILURE:'LOGIN_REQUEST_FAILURE',
    LOGOUT:'LOGOUT',
    SIGNUP_REQUEST_SUCCESS:'SIGNUP_REQUEST_SUCCESS',
    STOCKGRAPH_SET_TIMESCALE:'STOCKGRAPH_SET_TIMESCALE',
}
