


export default {
    COINBASE_OAUTH_SUCCESS:'COINBASE_OAUTH_SUCCESS',
    
    //Sign Up
    INITIATE_SIGNUP_REQUEST:'INITATE_SIGNUP_REQUEST',
    SIGNUP_REQUEST_SUCCESS:'SIGNUP_REQUEST_SUCCESS',
    SIGNUP_REQUEST_FAILURE:'SIGNUP_REQUEST_FAILURE',

    //Login
    INITIATE_LOGIN_REQUEST:'INITIATE_LOGIN_REQUEST',
    LOGIN_REQUEST_SUCCESS:'LOGIN_REQUEST_SUCCESS',
    LOGIN_REQUEST_FAILURE:'LOGIN_REQUEST_FAILURE',
    
    //GDAX Coin Requests --> Coin name will be prefixed
    INITIATE_GDAX_REQUEST:'_INITIATE_GDAX_REQUEST',
    GDAX_REQUEST_SUCCESS:'_GDAX_REQUEST_SUCCESS',
    GDAX_REQUEST_FAILURE:'_GDAX_REQUEST_FAILURE',

    //Coin balance requests
    INITIATE_BALANCE_REQUEST:'INITIATE_BALANCE_REQUEST',
    BALANCE_REQUEST_SUCCESS:'BALANCE_REQUEST_SUCCESS',
    BALANCE_REQUEST_FAILURE:'BALANCE_REQUEST_FAILURE',


    //Logout
    LOGOUT:'LOGOUT',
    
    STOCKGRAPH_SET_TIMESCALE:'STOCKGRAPH_SET_TIMESCALE',
}
