export default {
    COINBASE_OAUTH_SUCCESS:'COINBASE_OAUTH_SUCCESS',
    LOGIN_REQUEST : 'LOGIN_REQUEST',
    LOGIN_REQUEST_SUCCESS:'LOGIN_REQUEST_SUCCESS',
    LOGOUT:'LOGOUT',
    STOCKGRAPH_SET_TIMESCALE:'STOCKGRAPH_SET_TIMESCALE',
}
